services:
  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - postgres_data:/var/lib/postgresql/data
    env_file: ./db.env
    ports:
      - 55432:${POSTGRES_PORT}

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "22181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_log:/datalog

  kafka:
    image: wurstmeister/kafka
    depends_on: [zookeeper]
    container_name: kafka
    ports:
      - "29092:29092"
    volumes:
      - kafka_data:/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "orders:1:1"

volumes:
  postgres_data:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
